version: "3.8"
services:
  app:
    build:
      context: .
    container_name: backend
    image: docvify
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=${NODE_ENV}
      - JWT_SECRET=${JWT_SECRET}
      - DB_NAME=${DB_NAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_SCHEMA=${DB_SCHEMA}
      - DB_HOST=host.docker.internal
      - ENCRY_ALGO=${ENCRY_ALGO}
      - BLOCKCHAIN_URL=http://host.docker.internal:9545
      - ENCRY_KEY=${ENCRY_KEY}
      - ENCRY_IV=${ENCRY_IV}
      - CONTRACT_ADDRESS=${CONTRACT_ADDRESS}
      - THIRD_WEB_CLIENTID=${THIRD_WEB_CLIENTID}
      - THIRD_WEB_SECRETKEY=${THIRD_WEB_SECRETKEY}
    networks:
      - docvify-network

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    image: angular_app
    volumes:
      - ./frontend:/usr/src/app/frontend
    restart: always
    ports:
      - "8000:80"
    networks:
      - docvify-network

networks:
  docvify-network:
    driver: bridge
  # mysql:
  #   image: mariadb:10.1.19
  #   ports:
  #     - 3307:3306
  #   volumes:
  #     - ./mysql:/var/lib/mysql
  #   environment:
  #     MYSQL_ROOT_PASSWORD: password
#   postgres:
#     image: postgres:latest
#     container_name: db_postgres
#     restart: always
#     # environment:
#     #   POSTGRES_USER: your_username
#     #   POSTGRES_PASSWORD: your_password
#     #   POSTGRES_DB: your_database_name
#     ports:
#       - "5432:5432"
#     volumes:
#       - postgres_data:/var/lib/postgres

# volumes:
#   postgres_data:
